#include<iostream>
#define MAX 100

using namespace std;

int main(){
cout<<"ssssssyyyyyyyyyyyhhhhhyyyhhhhhyhhhhhhhhhhhhhhhhhhhhhdmmmmmddddhhyysoyyssssssssssoooooooooossssssssssssssssoooooooooooooo+oo++++/////::::://///////////";
cout<<"ssssssssssssyyyyyyyyyyyyyhhhhhhhhhhhhhhhhdhhhhhdddmmmmmmmdddhdhyyoosyysyysssssssssssoooosssssssssssssssssssoooososooooooo++++/////////////////////////";
cout<<"sssosssssssyssssssyyysyyyyyhhhhhhhhhhhhhdddhhddmmmmmmddhhhhyhy+oososyyyyyysssssssssssossssssssssssssssssssssssssssooooo++++///////////////////////////";
cout<<"ssssssssssssssssssssssssyyyhhhhhhhhhhhhhdddddmmmmddhhhhhyhhyhysoydsohhyyyyysssssssssssssssssssssssssssssssssssssssooooo+++++/+////////////////////////";
cout<<"yssssosssssssssssssssssssyyyyyyyyhhhhddddmmmddddddhhhhhhyhhhhyo+ydyyhyyyyyyyyysssssssssssssssssssssssssyyyyysssssooooooo+++++++++/////////////////////";
cout<<"sssssssssssssssssssssssssyyyyyyyyhhhddmdddddddhdhhhhhhhhhhhhyso+hhhhhyyyyyyyyysyssssssssssssssssssssyyyyyyssssssooooooooooo++++++////////://////////::";
cout<<"ooooosooosssoosssssssssssssyyyyhhddmmdddddddhhhhhhhhhhyyhhhysyo+hhhhhhhhyyyyyyyyyssssyyssssssssssssyyyssssssssssssssssoooooo+++++//////////////////:::";
cout<<"oooooooooosooosoossssssssssyyhddddddhhhhhhhhhdhhhhhhhhyssssssyo+yhhhhhhhyyyyyyyyyyyyyyyssssssyysssssssssssssssssssssssssoooo++++++////////////////::::";
cout<<"ssoo+ooooooooosossssssssyhhddddhdhhhyyyyyhyhhhhhyssssssoossssss+yhhhhhhhhyyyyyyyyyyyyyyyyyyyyyssssssssssyyyyyyyyssssssssooooo+++++//////////////::::::";
cout<<"osssssso+oooooossssssyyhdmddhhhyyyssssyyyyyyyyssssoosssossssshs+shhhhhhhhhhyyyyyyyyyyyyyyyyysssssossssyyyyyyyyyyyyyyyssssooooo+++++/////////////::::::";
cout<<"++oooossssssooossosssyyyydhyssssssooosyysssoooosyyssssssssyssyho+hhhhhhhhhhhhhhhyyyyyyyyyyssssssssssssyyyyyyyyyyyyyyyssssoooo+++++++///////////:::::::";
cout<<"sssosssoossssssssssoosyssyoosoosssoosssssoososssyyyyysssssssoyho+yddhhhhhdhhhhhhhyyyyyysssssssysssssyyyyyyyyyyyyyyyysssssoooooo++++++///////////::::::";
cout<<"ysssysssssssssssoooooosssoooooosssssssssssooossssssysoooosyo+sy/+yddhhhhhdddhhhyyyyysyyyyyyyyyyyyssyyyyyyyyyyyyyyyyyyysssssoooooo++++///////////::::::";
cout<<"ssssssssyyyyyyyyyysssssssssssssssyyyyyyssssooooossssoo+ososo+oo/+shyyssyyhhhhyyyyyyyyyyyyyyyyyyysssyyyyyyyyyyyyyyyyyyyyssssssoooo++++//////////:::::::";
cout<<"ysssssysyyyyyyyyyyyyyyyyssssssyyyyyyyyssooooooo+///::-..``.-://:///////////-:/ossssssyyyyyyyyyysssssyyyyyyyyyyyyyyyyyyyyyssssoooo+++++/////////:::::::";
cout<<"sssyyyyyyyyyyyyyyyyyyyyysyssssssyyyyssooo+++:.`````.....``:::/----....--//+/:/+oo+++++osyyyyyyyssssssyyyyssyyyyyyyyyyyyyysssooooo++++++///////::::::::";
cout<<"yssyyyyyyyyyyyyyyyyyyyyysssssssssssoo+::::-`  ``.----::/:-::::........---+//////o+ooo+ooosyyyyyssssssyyyyyyyyyyyyyyyyyyysssssoooo++++++///////::::::::";
cout<<"yyyyyyyyyyyyyyyyyyyyyyyyssoosoossss+/:-:--...........-/:-....``.......---:-:-```.://++ssssssyyyysssssyyyyyyyyyyyyyyyyyyyyssssoooo+++++//////////::::::";
cout<<"yyyssyyyyyyyyyyyyyyssssoosooosssoo+:-`--...---.``````.-..  `.`.--::///+++++so:` .//++++oosoosyyyyysssssysssyyyyyyyyyyyyyssssoooo++++++++////////::::::";
cout<<"sssossssssssssyyyysssssosssoooss/-.-` ` `--:.````..-----:+//soyhyyyhhhhhdddNNdy+hddyosooooss/osyyysssssssssyssyyyyyyyyyssssoooooooooo+++////////::::::";
cout<<"ooossssssssssssyyyssssssssssooo+````````.:::..--..----:yyyyhdmmmNmmNNNNNNNNNNNmdmmNmyyysoosysoosssssossssyssosyyyyyyyyyyssssoooooooooo+++///////::::::";
cout<<"sssssssyyyyyssyyyyysssssssssoo+-`. .---:-----------:/+ymmmmNNdoyNNNNNNNNNNNNNNNdyydmmmmdhyssssosssss+/oossssssyyyyyyyyssssssssoooooooo+++///////::::::";
cout<<"ssssssyyyyyyyysyyssssssssssoo+:.-..---:-....----::/oshmNNNNNNhoshNNNNNNNNNNNNNNNmdddddmNNmdyyyssossss+o+/osyysyyyyyyysssssssssoooooooo+++////////::::/";
cout<<"ssssssssyysyyyssssssoooooooo+/-::-..`.:.  `-/::+oshmmNNNNNNmmyooodNNNNNNNNNNNNmNNNmddmNNNNNNNNmh+osssso//oyyssyyyyyyssssssssssoooooooo+++////////:::::";
cout<<"sssssssssssssssssooo++++oooo/-::-.` ``.```/+ydhdmmmmNNNmhyyyssysosmNNNNNNNNNNmNNNNNNmmNNNNNNNNmNmsoosyso+ossssyyyyysosysssssssssssooooo+++///////::///";
cout<<"ooooooooooosoooooo+++ooooooo--:-.` `...-++oydmmmmmmmmmmmysoossydhhmNNNNNNNNNNmmmNNNNNNmmNNNNNNNNNmysosyysssssyyyyyysooyyyysssssssssoooo++++///////////";
cout<<"oooo+o++oooooooooooooooooo+---..```...-oyhdmNmmdmmmmmmmmNNmdyoodNNNNNNNNNNNNNmhhmNNNNNNNNNNNNNNNNmdhsssyssyyyyyyyyyysoyyyyysssssssooooo++++///////////";
cout<<"+ooo+o++oososoooooooooooo+:```::..`..-/dmNmmdddddddmmdmmNNNNNmmNNNNNNmmNNNNNmmhydmNNNNNNNNNNNNNNNNNmhyyyyyyyyyyyyyssssyyyyysssssssosoooo++++//////////";
cout<<"ooooooossssssoooooooooooo+.`.:---..-:+odNmdmmmdddddmdmmNNmmmNNNNNmmmmmmNmmNNNmmmNNNNNNNNNNNNNNNNNNNNmdyyyyyyyyyyssssosyyyyyyssssssssooooo++++++///////";
cout<<"ssssososssssooooooooooooo/`.-/----::+ymmdddmmmddddmmdmNmmmNNmmmmmmmmddmNmmNNNmmmNNNNNNNNNNNNNNNNNNNNNmmdyyyyyyyyosyyhyosssssosssssssoooooo+++++///////";
cout<<"ssssoossssooooooooooooooo:...::--:oohmddhhmmdddmdmdddmNmmmmmdmmmmddhddmmmmmNmdddmmmmNNNmNNNNNNNdymNNNNNmdhhhyyyysyhdysyssyssoossssssssoooo+++++///////";
cout<<"oosoossssoooooooooooooooyy:..`-+yhdmmhhhhdmddddddmdddNmddmmdddmmhhhyyhdddmmmmhyddmmmmmmdmNNNNNNhodNNNNNNmdhhyyyyyyhysysosssyysssssssssoooo+++++///////";
cout<<"ssssoooooooooooooooooooshd/-` .:oydhdhhhhdmddhddhdddmmdhddddddddsyyssshhdddmmysdhddmmdmdmNmNNNNNhymNNNNNmmddhyyyyyysooosyyyyyyyysssssssooo++++////////";
cout<<"sssssooosooooooooooooosydms/` ./ydhhhhyhdmdhhhdhhdddmmdydddhdddyossssssydhdmhssdydhddddddmmmmNNNmhymNNNNNmmmdhhhyyyyyyyyyyyyyyyysssssssooo++++////////";
cout<<"ooooooooosoooooossssssshmNmo-:ssdhhdyhyhdmhhhhdhhdddmdhymdhhhhhsosooossydhddssyhyhhhhhhdhmmmmmNmNmhhdNNNNNNNmdhhyyyyyyyyyyyyyyyyssssssssoo+++++///////";
cout<<"ooooooosssososssssssssydmNm+-+ddhyhhyhyhdmddyhhyyhhmmhhdmhyhyhysosooosyyhydhoosyyyyyyysdhmmdmmmdmNhssdNNNNNNmdhhyyyyyyyyyyyssysyysyyyyssoo+++++++/////";
cout<<"oooooosssssssssssssssshmmNm-.shhsyhyyhhhdddhydhyhdhmmddmdyddhhysysoooyhhhydsoosssssssssdhdmddddddNmysdNNNNNNNmdhhyyyyyyyyyyyssssysyyyyssooo++++++++///";
cout<<"+oooossssssssssssssssshmmNm-/sysyhhyyyhdddmhsdyyhhdmmmmmddmdddhydhhhhhddhyhoooossssssoyhhddddddhdmNdymNNNNNNNmdhhhyyyyyyyyyyyyyyyyyyyyssooo+++++++++++";
cout<<"ooooossssssssssssssssydmmNy./yhyhhhyyyydddmhsdshyddmmmmmdmdddhyyysyhhddhyhsoooossssssoyydddmmmdmmNNNNNNNNNNNNNmdhyyyyyyyyyyyyyyssyyyysssooo+++++++++++";
cout<<"sssoossssssssssssssssydmdNy+ds+yhhhyysshmhdyyyohshmmNNNNmdyyyoos++oyhddyyyooooooooososhhddddddyhdmNNNNNNNNNNNNNmhyyyyyyyyyyyyyyysyyyysysoooo++++++++++";
cout<<"sssoooooossossoooooosyddmNhs:-oyhyysssyhmddsyyyyshmNNNNNdyoys+yo++oydddhyooo+ooooo+soyyhhddhysoosymNNNNNNNNNNNNmdyyyyyyyyyyyyysyysyssssssoooo+++++++++";
cout<<"ooooooo+++oooooooo+oshmdmNds./oyhyssysyhmdhsyydysdNNNNNdhsoysoh++oshdhdhsoo+osoo++ossyyhhhhys++ooydmNNNNNNNNNNNmhyyyyyyyyyyyyyyyyyyysyysssooo+++++++++";
cout<<"oooooooo++++oo+oo++osdmdmNdh/+yyhyssssydddhyhydsydmNNmhyossyhdmhhhydhhdyoo++o++///oossyhhhyyo+oooshmNNNNNNdmNNmyshyyyyyyyyyyyyyyysysssssssooo+++++++++";
cout<<"o+ooooo++++++++++++sydmdmmmdooyhyyssssyddmhhyydssdmmhyssyhdydNNddmssyyo++/////:-://++ossyhddddssdmdmNNNNNNysyhyyydhyyyyyyyyyyssssssssssssoooo+++++++++";
cout<<"ooooooo+++++++++++osydmdddmyosydysssosdddmyhshmssdmhssssyysosmNmmd/:/os+/:::------::///+smmhdd+/odmmNNNNNNNhyhhysmdyyyyyyyyyysyssssssssssoooo+++++++++";
cout<<"sossoooo++++++++++osymmmdmdssshhhyososhmmdyyohmsydmsoooooo+++oyys+//+++/:::--------::::++yhdho/+oyhhmNNNNNNmydNdmmmhyyyyyyyyyyysysysssssssooo+++++++++";
cout<<"ssssssoooo++//++++oyhmmdhmyssyhhyyoo+sdmmhhhsdmoyddo++////////////////::-----------::::://++++++osssdNNNNNNNNNNNNNmdyyyyyyyyyyyyyyyyyyssssooo+++++++++";
cout<<"yysssssoooo++o+++oosdmmdhdsosyhyyyoo+shmmydysdmyhdd++/:::::::::::::::---------------::::::://///+++oyNNNNNNNNNNNNNmmhyyyyyyyyyyyyyyyyyssssooo+++++++++";
cout<<"ysssosoooooooo++osssdmmmdyoosyysyyoooyhNdydsodmhddh+/::::::-------------------------------:::::////+smNNNNNNNNNNNNNmdyyyyyyyyyyyyyyyyysssooo++++++++++";
cout<<"sssoooooooooo++oosshmmmdhsooshysyyoosyhNdyy+ohmyhdy+/::::----------------------------------:::::://+smNNNNNNNNNNNNNmdhyyyyyyysyyyyyyyssssoo+++++++++++";
cout<<"ooosooooooooo+oosyydmdmdsoooyhssyysosyhmyyh+shmyhds+/::::-----------------------------------::::::/+omNNNNNNNNNNmNNNmhyyyyyyssssssssssssooo+++++++++++";
cout<<"ooososooooooooosyyhddmmhsoossyysyysosyhNyyhsydmhhhs+//::-------------------:::--------::-----:::::/+sNNNNNNNNNNNmmNNmdyyyyysssssssssssooo+++//////++++";
cout<<"oosyssoooooooooyyyhmdmdys+osyysssyossyhmsydshmmsyhs+/:::---------------:::::::--------::-------:::/+yNNNNNNNNNNNmmmmmmhyyyyssssssssooooo+++//////////+";
cout<<"sssysssoooooooosshdmhmhy++ossysysyooyssdssy/oddyydso//::-------------://::::::----.---::--------::/+dNNNNNNNNNNNddmmmmhysssssssssssoooo++++///////////";
cout<<"ssssssssooooooosshdmhmso/+oo/+sssshhhs+hyoo-:yyyhdso//::-------------:/:-:::----------::---------:/omNNNNNNNNNNmdddmmmdyssssssssssoooooo++////:///////";
cout<<"ossssssoo+o+++osyhmddhs++oosyssyyhydyyydhyy+ymhyddso+/::-------------:/:-----:::----:::---------::+hNNNNNNNNNNNmdddmmmmyyysssssssoooosso+////:://///++";
cout<<"ossssoooo+oo+oyyydmdmho+ossyhsosssssshddddyohmhyddyo+/::--------------:/:::::::/:::///:--------::/omNNNNNNNNNNmmmmdmmmmyyysyysssssssssso++///////+++++";
cout<<"ososoooooooooosyydmhdso+ossyyosyyoo+shddddyyhmhyhdyo+/:::---------------::::------::::---------:/+hNNNNNNNNNNNmmmmmmmmmhyyyyhhyysssssssoo+++////++++++";
cout<<"ososoooooooo++osydmhhooooooyyohyyo+/shdmmmdhdmhsydyso//::::----------------------------------::/+yNNNNNNNNNNNNmNmmmmmmmdhdhddhhyyyyyysssoo++++++++++++";
cout<<"osossssoooooo+oosdmhso+ososhooyyyoo+ydmmmmdddmhoydhso+/:::::::---------------------------:::::/+smNNNNNNNNNNNNNNNNmmmmmmddddmmdddddhhyyysoo+++//////++";
cout<<"+ooossoooooossossddhoo+oooyyoossyssoddmmNmmmmmyshhdyso+/:::::::::///::::::::::::::://::::////+shmNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdddddddddhhyoo+++//////+";
cout<<"+oooosssooooyysyyddhso+oosyy++ssyyyydmmmNmNNmmdshddhss+//::::::///++++++++ooooooooooooo+////osyhmNNNNNNNNNNNNNNNNNNNNmNNmmmmmmmmmddddddddhhysso++/////";
cout<<":oooosssoooossyhhddhsooossss++oyhdhhmmmNNNNNNmmshdmdhys+///:::::::/++ooooooooooooooooo+////+///+hNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmdddddddddhhhhys+///";
cout<<":oooosssoooooyyhhddysooosssss+sdydhdmmmNNNNNNmmyddmmmdhyo+////::::://+++++++++++++++++///++/::/smNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmddddddhhdddhhhys+/";
cout<<"-/ooossssssooshdhddyyossyysssoydddddmmmNNNNNNNmdddmmmdsoooo+/////:::////////++++++/////+s+:::/omNNNNNNNNNNNNNNsyNNNNNNNNmmmmmmmmmmmdmmmmdhhdddhhhhhhso";
cout<<"-/+oossssssooosddmddhyyyhhyyyyddmmddmmmNNNNNNNmmddmmms+///oso++//////////////////////+sy+/::/omNNNNNNNNNNNNNNh+oNNNNNNNmmmmmmmmmmmddmmmdddddhhhhhhhhhy";
cout<<"-:/oosssssssoooydddmdhhdddhhhhmmmmmmmmmNNNNNNNNmmmmmmds+++/+so++++/////////:::://///oss::::/yNNNNNNNNNNNNNNNhsoomNmmNNNmmmmmmmmmmdmmmmddddhhhhhhhhhhhh";
cout<<"::/++sssssoosoooyhdmmdddmdhhddmmmmmmmmmNNNNNNNNmmmmmmmdyo+//+ss+++///////////:::///ss+:--:/yNNNNNNNNNNNNNNNd+oooooo+sdmmmmmmmmmmdmmmmdddhhhhhhyyyyyyyh";
cout<<":///+ssssssooo+ooshmmddmmmdymmmmmmmmmmNNNNNNNNNNmmmmmmmdhso+//oso++/////////////+sso/:---:yNNNNNNNNNNNNNNNNmyds+++sdmNmmmmmmmmmddddmdhhhhhhyyyyyyyyyyy";
cout<<"::///ossooooooooooohddmmmmmhmmmmNmNNmmNNNNNNNNNmmdmmmdhddhs+/:://++oo+++++++osyhmy+/:::-:oNNNNNNNNNhNNNNNNNNNNssymNNNNNmmmmmmdddddddhhhhhyyyyyyyyyyyyy";
cout<<"/:::/ossoooooooooooshdmmmmmdmmmmNNNNmmNNNNNNNNNyyodmmmhhhhhso+/::::/ooosshdmmmmdy+/::::/omNNNNNNNNh+dNNNNNNNNNNNNNNNNNmmmmmmdddddddhhhhyyyyyyyssssssyy";
cout<<"//:::+ssssosooooooooshdmmmmmmNmNNNNNNNNNNNNNNNNd/+smmmhyyyhhso+/:---:+oosyyyyhhy/:----:omNNNNNNNNNyosmNNNNNNNNNNNNNNNNmmmmmddddddddhhyyyyyssyssssyyyyy";
cout<<"//:::+ssssssoooooooooydmmmmmmNNNNNNNNNNNNNNNNNNm+//hmmdsyysyyo+/:----:+oossyyhy+:-----+mNNNNNmyhhhssosNNNNNNNNNNNNNNNmmmmmmmdddmmdhhyyyyyssssssyyssyss";
cout<<"//::/+sssssssossosoooshhshdmmNNNNNNNNNNNNNNNNNNNh:/+mmmoossssso/::----:/+oyyys+/:---:+dmNNNNNhsoooshhmNNNNNNmmNNNNNNNmmmmmmmmdmmmdhhyyyyyssssyssssssss";
cout<<":/:///osssssssssssssss/+oodmmmNNNNNNNNNNNNNNNNNNNo:/ymmy-/ossso+/:------::////::----+hdmNNNNNNNmdyymNNNNNNNmmmNNNNNNNmmmmmmmmdmmmdhhyyyyyyyyssssssssss";
cout<<":::///osssssssssossoo/``+ymmmmNNNNNNNNNNNNNNNNNNNm++-hmd+`.:/+oo+/:--------::::----/yhdmmNNNNNNNNNNNNNNNNNNmmmmNNNNNmmmmmmmmmmmmmdhhyyyyyyssssssssssss";
cout<<"--:/+/osssssssssossoo-./sddmmmmNNNNNNNNNNNNNNNNNNNh-`-hdd-```-:///:---------------:+osdmNNNNNNNNNNNNNNNNNNmmmmmNNNNmmmmmmmmmmmmmmdhhyyyyssssssssssssss";
cout<<"--:///osssssssssooooo+ossyhdmmmmNNNNNNNNNNNNNNNNNmh:`./hdy`  ```-+:------------.--:/+sdmNNNNNNNNNNNNNNNNNmmmmmNNNNmmmmmmmmmmmmmmmdhhhyysssssssssssssss";
cout<<"--:///osssssssssooooosssssshhddmmmNmNNNNNNNNNNNNNNNmo+//dds`   `.+/:---------------:+ydmmmNNNNNNNNNNNNmmmmmmmmNNmNmmmmmmmmmmmmmmmddhhyysssssssssssssss";
cout<<"-::://osssssssssooossssssyyyyhhhddmmmNNNNNNNNNNNNNNNNmy//ddy.```-+/:----------...--:/oyddmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmdddhyssssssssssssssss";
cout<<"---://osssssssssosssssssssyyhhyyyyydmNNNNNNNNNNNNNNNNNNds+hdh:``://:::---------------:/+oossdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhyssssssssssssssss";
cout<<"---::/ossssssssssssossssssssyhhysooshmmmmNNNNNNNNNNNNNNNmdydmd+.--::::::----------..----::/+smmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmmddhhyssssssssssssssy";
cout<<"---::/ossssssyyysooossyyyssysyddysoshmmmhhmNNNNNNNNNNmmmmmmddmmy:..-:::::------------------/oddmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmmdddhysssssssssssssss";
cout<<"----:/osssyyyyyssoooosyhysyyyyyddyssymmmdyydmmdhdddddmmmddddddmmho-.--::-------------------/odmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmddddhsssssssssssssss";
cout<<"----:/osssyyyyyssooossshdhysyyyydysyhdmmmhsymmmyysssyyhhhhhdddh/os+-.---------------------:+hdmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmNNNNmmddhyssssssssssssss";
cout<<"----:/sysyyyyysssossssssydhyysyyyyyhhddmmh+:ohddyssssyyyhhhhhdh``...``....---------------:+hddmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmNNNmmmddyysssssssssssss";
cout<<"-----:oysyyyyyyssssssssssyddhyyyyhhhhhddmds/+ymmdysssyyyhhhhddh.      ``......----------:/yddddmmmmmmmmmmmmmmmmmmmmmmmddddmmmmmNNNNmmmdhyyssssssssssss";
cout<<"----.:syyyhyyyysssssssssssyhddyyhhhhhhhdmmmhyydmmhyysyyhhhhhhdh.       ```....---------::+mddddmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmNNNNNmmddhyysssssssssss";
cout<<"---..:syyyhhyyyyssssssssssssyhdhhhhhhhhhdmmdhyhdmmdyyyyyhhhhhhh.       `````..---------:/hmmmddmmmmmmmmmmmmmmmmmmmmmmdddmmmmmmmmNNNNNmmddhysssssssssss";
cout<<":--..-oyyyhhyyyssssssssssysysyyhddddhhyhddmmmhyhmmmdhyyyyhhhhhy`       ````...-...----:/ymmmmdddddmmmmmmmmmmmmmmmmdddmdmmmmmmmmmmNNNNmmmdhyyyyysssssss";
cout<<":--..-oyyyhyyyyssssssssssyyyyyyyhddddhyyhdmmmmyydmmmmdyyyyyhhho        ````......----:/ymmmmmddddddddmmmmmmmmmmmmmddmmmmmmmmmmmmNNNNNNmmmhyyysssssssss";
cout<<"--...-oyyyyyyyyssssssssssyyyyyyyyhhddmdyhhdmmmdyhdmmmmdhyyyyhh+       `````......---:/ymmmmmddhhhhhhdddmmmmmmmmmmmmmddmmmmmmmmmmmNNNNNNmmhyyysssssssss";
cout<<"--...-syyyyyyyyssssyyyssyyyyyyyyyhhhddmdhhddmmmhyhdmmmmdhyyyyy-       ``````....---:+ymmmmmmdhyyyhhhhhdddddmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmhyyysssssssss";
cout<<"--...:oyyhyyyyssyssyyyyyyyyyyyyhhhhhhddmdhddmmmdyyhdmmmmmdyyy/       ```````....--:+hmmmmmmmhyyyyyyyhhhhdddddmmmmmmmmdmmmmmmmmmmmmNmNNNmmdhyyyyyysssss";
cout<<"--...:syhhyyssssyyyyyyyyyyyyyhhhhhhddddmmdhddmmmyyhhddmmmmdyo`       ``````.....-:/hmmmmmmmdhyyyyyyyyhhhhhddddmmmmmmmdmmmmmmmmmmmmmmNNNmmmddhhdddyssss";
cout<<"::...-syhhysssssyyyyyyyyyyyhhhhhhhhddddmmmhhdmmmhhhhhddmmdhs.      ```````....--:/hmmmmmmmmdyyyyyyyyyyhhhhhdddddmmmmddmmmmmmmmmmmmmmmNmmmmdy//yhhyysss";
cout<<"/:-.--ohhyysssssyhhysyyhhhhhhhhdddddddddmmmhdmmmdyhhhhhdmmdo      ````````....--/hmmmmmmmmmdyyysyyyyyyyhhhhdddddddddddddmmmmmmmmmmmmmmmmmmmdo+oyyyssss";
cout<<"/:-..-+sso++osssyhhhysyyhhhhhhhddddddddmmmmmddmmmhhdhhhhddh.     ```````````..-:ymmmmmmmmmmdyy-`./+syyyhhhddddddddddhhddmmmmmmmmmmmmmmmmmmmdyooossssss";
cout<<"+:---:/o+++++sssyyhhhyyyyhhhhhhhhddddddmmmmmddmmmyhddhhhhh+     ``````````..-::odmmmmmmmmmmho+.    `.:+hhhddddddddhhhhddmmmmmmmmmmmmmmmmmddoosysssssss";
cout<<"+/---//++++oosssyyhddhyyyyhhhdhhhddddddmmmmmmdmmdyhdddhhhs`    ````````...-::/+hmmmmmmmmmmm+`..-::  ..-yhhddddddddhhyhhdmmmmmmmmmmmmmmmmmmhooyssysssss";
cout<<"+/::/++sssssosyyyyyhddhyyyyhhhhddhhdddddmmmmmddmdyhdmddhy-   `````......--:///smmmmmmmmdddhyoosyys- /yyhhhddddmmmdhhyhhdmmmmmmmmmmmmmmmmmmhooyyyysssss";
cout<<"o////+oysyysssyyyyyyhddhyyhhhhhhddddddddmmmmmmddhyhdmmdh/`  ````.......--:///+hmmddhhyyyhddh:`/yyys.`ohhhddddmmmmddhhhhdmmmmmmmmmmmmmmmmmmdsosyyssssss";
cout<<"o++//+osyyysssyyyyyyyyhhhhhhhhhhhdddddddmmmmmmmhhyhdmmdo` `````......---:////shhyyyhhddmmmmh/ `+syyo`.shdddmmmmmmmdhhhhdmmmmmmmmmmmmmmmmmmdyssyhhsssss";
cout<<"++++++osyyysyyyhyyyyyyyyhhhhhhhhhdddddddmmmmmmmmhhhdmdy.``````.....----:////+hmmmmmmmmmmmmmho` `-+yy+`:yddmmmmmmmmdhhhhdmmmmmmmmmmmmmmmmmmmhyyyddhysss";
cout<<"++++o+osyyyyyyydhyyyyhhhhhhhhhhhhddddddmmmmmmmmmmddddh-``````.....---::///++sdmmmmmmmmmmmmmss.   `/sy/./hdmmmmmmmmdhhhhdmmmmmmmmmmmmmmmmmdmdhhhdmdhyss";
cout<<"++ooooosyyyyyyddhyyyyyhhhhhhhhhhddddddddddmmmmmmmmddh:``````.....---:://+++ohmhhdmmmmmmmmmd++/ ` `ohhho/sdmdmmmmmmdhhhhdmmmmmmmmmmmmmmmmmmddhhhdmmdhys";
cout<<"ooooooossyyyydmmhyyyyyyhhhhhhhhdmmmmmmmmmmmmmmmmmmdh/`````.....---:::/+++ooymmmhyhdmmmmmmmmo/+````:yhddyoshsshmmmmmdhhhdmmmmmmmmmmmmmmmmmmmddhhdmmmdhy";
cout<<"ooooooosyyyyhmNNmyhhyyyhhhhhhhhdmmmmmmmmmmmmmmmmmmm+````.....---::://++++oshmmdhshddhdhyhmmo//:`++.:hdddsosyhmmmmmmdhhddmmmmmmmmmmmmmmmmmmmddhddmmmmdd";
cout<<"ssooooosyhhhhmNNmhhhyyhhhhhhhhdmmmNNNmmmmmmmmmmmmd+.```....---:::///+++oooyddhhsoyyyyhhyddds++/`:y+:odddhyyhmmNNmNmdhhdmmmmmmmmmmmmmmmmmmmmmdddddddddd";
cout<<"yyyyyyyyyhhdmmmmmhhhhhhhhhhhhdmmNNNNmmmmmmmmmmmmd/.......---:::://++oooooyhdhydhyyyyyyhhhdmdhhyosyyysyyyyhhmmNNNNNNdhhdmmmmmmmmmmmmmmmmmmmmmdddddddddd";
cout<<"hhhhyhyhhhddddhhhhhhhhhhhhhdmmNNNNmmmmmmmmddmmmy-......---:::////++ooossshddhdhhyyyhhhhhhhho//:-..-:+shdddmmmmmmNNNdhddmmNmmmmmNmNNNmmmmmmmmmmdddddddd";
cout<<"yyyysoosssoooo+++shhhhhhhhdmNNmmmdddddddddmmmdo-.....---:::///+++ooosssyydddhhyhdmNNNNNNmmd+://+osyhddmmmmmmmmmNNNNdhdmmNNNmmmmmNNNNNmmmmmmmmmdddmmmdm";
cout<<"+++//////////////+hhhhhhhdmmmmdddddmmmmmmmy+s:......--::////+++ooossyyyhdddhhmmNNNNNNNNNNNmhhhhhhdddmmmmmmmmmNNNNNmhddmmNNNNNmmmNNNNmmmmmmmmmmmddddmdd";
cout<<"//////////////////yhhhhdddmmmmmmNNNmmmNNdo.  `...---::///++++oossyhyhhhdmmdmNNNNNNNNNNNNNNdddhhhddmmmmmmmmmmNNNNNmdhdmmNNNNNNNNNNNmmmmmmmmmmmmmddddddd";
cout<<"//////////////////sddddddmmNNNNNNmmmmNNNmho--://////+++++ooossyyyhdddddmNNNNNNNNNNNNNNNNNNdddddddmmmmmmmmmmmNNNNNmdddmNNNNNNNNNNNNmmmmmmmmmmmmmmddhdhd";
cout<<"////////////////++odddddmmNNNNNNmmmmmmmmmmmhddmmmmmdddddhhhhhhhdddddmmmmNNNNNNNNNNNNNNNNNNmddddddmmmmmmmmmmNNNNNNmddmmNNNNNNNNNNNNNNNNNmmmmmmmmmdddddd";
cout<<"////////++++++++oosddddmNNNNNNNmmmmNmNNNNmmmNNNNNNNNNNNNNNNNNmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNmmddddmmmmmmmmmmNNNNNNmdmmNNNNNNNNNNNNNNNNNmmmmmmmmmmmddddd";
cout<<"++++++++oooyyhhdmmmmddmNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmdmmmmmmmmNNNNNNNmdmmNNNNNNNNNNNNNNNNNmmmmmmmmmmmmddddh";
cout<<"+ooooshhdmmNNNNNNNNmdmmNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmddd";
cout<<"yddmmNNNNNNNNNNNNNNmmmNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmddd";
cout<<"NNNNNNNNNNNNNNNNNNNmmmmNmmmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmddd";
cout<<"NNNNNNNNNNNNNNNNNNNmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmdd";
cout<<"NNNNNNMMNNNNNNNNNNNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNMNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmddd";
cout<<"MMMMMMNNMNMNNNNNNmmmmmmmmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNMMMNNNNMMMMMNNNNNNMMMNNNNNNNNNNNMNNNNNNNNNNNNNMMMMMMNMMNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmddd";
cout<<"NNNNMMMNMMMNNNNNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMNMMMNNNNNNNMMNNNNMNNMMMMMMNNNMMNNMMNNNNNNNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmdd";
cout<<"NNNNNMMMMNNNMMNNNmmmmmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNNNNNNNNMMMNNNNNNMMMMMNNNNNNNMMMMMNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmddd";
cout<<"MMNNMMNNNNNNMNNmmmmmmmmNmNNNNNNNNNNNNNNNNNNNNNMMMMNNNMNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmdd";
cout<<"MMMMNNNNNNNMMNNmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNMMMMMMNMNNMMMMMMMMMNNNNNMMMMMMMMNNNMMNNMMMMMNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmd";
cout<<"MMMMMNNNNMMMNNNNNmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNMNMNNMMMNNNNNNMMMMMMMMMNNNNNNNNNMMMMNNNMNNMMMMMMNMMNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdd";
cout<<"MMMMMMMMNMMNNNNNmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMNMMMMMMNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmdd";
cout<<"MMMMMMMMNNMNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNMMMMMMMMMNNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmddddhy";
cout<<"MMMMMMMMMMNNNmmmNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmdddhs:-";
cout<<"MMMMMMMMMMNNmmmNNNNNNNNNNNNNNNNNNNNNNNNMMMNNNNMNNNNNMMMMMMMMMMMMNMMMNNMMNNMNNNNNNNMMMMNNNMMMMNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmddddy+``";
cout<<"MMMMMMMMMNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNMMMMMMNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmdddddhs/-..";
cout<<"MMMMMMMMMNmNNNNNNNNNNNNNmNNNNmmNNNNNNNNNNNNNNNNNNNNNNMNMNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdddhs/-...-";
cout<<"MMMMMMMMNNNNNNNNNmNNNmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmmmmmmddddhs/-......";
cout<<"MMMMMMMNNNNNNNNmNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmddds/-........";
cout<<"MMMMMMMNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmddddddy/-..........";
}